### ISSUE TITLE
Add drop-down list of bluetooth devices

### ISSUE THREAD

**Issue by go226** [naubiomech/ExoGui#14]
Add a drop-down menu for bluetooth devices so we don't have to keep changing the bluetooth index. Will require moving the bluetooth object creation process to another section of the code - probably Connect_BT_Callback

**Comment by go226** [comment]
Added a drop-down menu with entries for all BT devices. Adding on new modules is very easy. The creation of the bluetooth object has been moved to "Connect_BT_Callback()". A new object is created for the selected module but when re-connecting to the same module the object is not recreated. Tested 5/23/19

**Comment by zflerner** [comment]
Sweet! Great addition.

Zach




On May 23, 2019, at 4:28 PM, Greg Orekhov <notifications@github.com<mailto:notifications@github.com>> wrote:


Added a drop-down menu with entries for all BT devices. Adding on new modules is very easy. The creation of the bluetooth object has been moved to "Connect_BT_Callback()". A new object is created for the selected module but when re-connecting to the same module the object is not recreated. Tested 5/23/19
