### ISSUE TITLE
Have an option to use the same baseline throughout several trials

### ISSUE THREAD

**Issue by go226** [naubiomech/ExoGui#8]
I had made a few changes to the GUI that would force a user to retake the baseline every time a trial was ended and restarted but this does not work for modes that need the same baseline throughout trials. Add an option to keep the baseline throughout trials (i.e. opt out of "forced" retake baseline)

**Comment by go226** [comment]
Added a checkbox to the GUI called "Reuse Baseline Next Trial" that is initially active. When this box is active, the control mode is maintained after ending and retaking the trial. When this box is inactive, the control mode is deactivated after ending trial and the baseline must be retaken in order to enter a proportional control mode. Needs testing

**Comment by aaclab-tamucc** [comment]
Tested with some changes to make them work.
